### ISSUE TITLE
Convert Apollo training documentation into GTN format

### ISSUE THREAD

**Issue by jrr-cpt** [TAMU-CPT/training-material#1]
@ToniNittolo Create GTN-format training materials on **Apollo** using the content provided at [the BICH464 documentation site](https://cpt.tamu.edu/bich464/). 

It is number 2 under both the Course and Student/Staff required reading sections, and the two Apollo pages are identical. There are three sub-sections:
2.1 Background
2.2 Annotation
2.3 Workflows
Combine them under the Genome Annotation topic as _"Getting Started with Apollo"_. 

All the original files associated with the current pages are found in the TAMU Github repository [CPT/BICH464-Computer-Lab/doc/](https://github.tamu.edu/cpt/BICH464-Computer-Lab/blob/master/index.rst). Use new screen shots as needed. 

@MoffMade please add appropriate tags/labels.

**Comment by MoffMade** [comment]
This was completed in forked repo by Toni, it has been merged into master in order to bring the changes over. In future, these tutorials will be done in a branch and then merged after review. 

Things so far:

- [ ] FASTA example image did not show on local copy
- [ ] jbrowse tool section should be updated to use the jbrowse+cpt tool as example, perhaps add tool link?
- [ ] Add a tip for the tools to note that the entry type needs to be "Direct Entry" for the typing in a name to work
- [ ] Check for typos/grammar.

cc: @ToniNittolo
