### ISSUE TITLE
Update "Additional Analyses" folder

### ISSUE THREAD

**Issue by meiliuCPT** [TAMU-CPT/training-material#104]
@jdc-cpt please update screenshots in "Additional Analyses" folder.  Note that we have made new Phage Comparative Genomics workflow (in shared data).  

Leave "Adding Custom Evidence Tracks to Apollo", "Loading Existing Genbank File into Apollo", "Re-opening an Existing Apollo Record with Annotations" to me, I tested those flows and need to re-write certain portions

**Comment by meiliuCPT** [comment]
"Re-opening an Existing Apollo Record with Annotations" is updated.  Need to put in the working flow link.

**Comment by meiliuCPT** [comment]
"Adding evidence track to Apollo" is re-written and updated.

**Comment by meiliuCPT** [comment]
“Upload Existing Genome into Apollo” is updated.

**Comment by meiliuCPT** [comment]
"Finding Interrupted Genes Using the Intron Detection Tool" is updated

**Comment by meiliuCPT** [comment]
"Generating the Genome Annotation Table" is updated

**Comment by jdc-cpt** [comment]
"Using HHPRed for Protein Analysis" Looks good. No updates needed.
"Advanced Lysis Gene Search" looks good. No updates needed.

**Comment by jdc-cpt** [comment]
"Phage Comparative Genomics Tools" needs some updating. Looks like a gff3 and xmfa file are needed. @meiliuCPT not exactly sure how this workflow is used, so I may need some help actually running the workflow in order to re-write. I think this tutorial will need some significant modification, so I will make a separate issue for it so that we can close this one and push the current changes today. That can go on the next push.

**Comment by jdc-cpt** [comment]
"Finding and Annotating Lysis Genes" looks good.
All issues except for the comparative WF look good, so I will close this issue and ask Cory to push the bich464 changes into the master.
