### ISSUE TITLE
Help needed to edit training tutorial templates

### ISSUE THREAD

**Issue by meiliuCPT** [TAMU-CPT/training-material#105]
(1) how to edit text on this page?  The top corner "view on Github" and "Gitter" under "help" lead to broken page
![image](https://user-images.githubusercontent.com/44712223/97084728-ae87f200-15de-11eb-8261-01816d00697a.png)

(2) How to get rid of the "Overview" box in tutorials in the "introduction to Galaxy and Apollo folder?  Every single tutorial has that and it does not serve any purpose for us
![image](https://user-images.githubusercontent.com/44712223/97084854-569dbb00-15df-11eb-952f-0fbcba1d126a.png)

(3) My name is listed as "meiliuCPT" under all contributors.  How can I change it to the proper real name like others?
![image](https://user-images.githubusercontent.com/44712223/97085326-75ea1780-15e2-11eb-8d3b-7baa70dcee69.png)

**Comment by MoffMade** [comment]
1) Test these links on the non-dev page, I think they are generated correctly for the live site instead of the dev site.
2) The Overview box is part of the template for hands-on tutorials, I think we can get rid of it by changing that layout file? We are able to fill out those entries in the metadata file if we want to make use of it.
3) Update your entry in the CONTRIBUTORS file at the root of the repository

**Comment by meiliuCPT** [comment]
1.  Those links are tested on the non-dev page, and are broken.  How do I edit the text on that page?

**Comment by MoffMade** [comment]
https://github.com/TAMU-CPT/training-material/blob/bich464/_layouts/home.html has the text. I'll merge what we have after updating your name and we can figure out the links. I think they are generated from one of the config files

**Comment by MoffMade** [comment]
The links break when you view them from within galaxy because of how that middle pane is rendered by the browser. You need to open it as it's own tab to follow those links

**Comment by meiliuCPT** [comment]
This issue was resolved
